### ISSUE TITLE
Not importing music

### ISSUE THREAD

**Issue by AbsoluteZero93** [jamesfairhurst/smart-playlists-for-spotify#15]
It is not importing my Spotify music so non of the playlists have any music in them.

![image](https://cloud.githubusercontent.com/assets/25151077/21982518/9b994f64-dbe4-11e6-8f15-8f036552b53f.png)

**Comment by jamesfairhurst** [comment]
Is your Spotify username AbsoluteZero93?

**Comment by AbsoluteZero93** [comment]
No, is that causing the problem?

**Comment by AbsoluteZero93** [comment]
Just logged into the account and now the music is there. Not sure what was happening.

Thanks!

**Comment by jamesfairhurst** [comment]
Just been fixing the issue! Glad it's working now!

Related to #13
