### ISSUE TITLE
Sync Tracks to remove songs no longer saved

### ISSUE THREAD

**Issue by csmed** [jamesfairhurst/smart-playlists-for-spotify#16]
Sync Tracks only seems to add songs to the list.
Now that i have unsaved songs, they never disappear from my Smart Playlists catalogue.
Can the "sync tracks" both add new songs and remove songs no longer saved?

**Comment by jamesfairhurst** [comment]
Will take a look, should work both ways. Thanks for letting me know!

**Comment by smartplaylistsquestion** [comment]
i want to echo what csmed said, I'll delete a song from my library but when i push my playlist back to spotify it will reappear as it's still listed in my tracks on here. I do want to say tho I really appreciate you creating this! Unbelievably useful -- if this was fixed it would be even moreso. Thanks man

**Comment by jstipe** [comment]
Is there an update on this. At this time, I still think songs removed from my library remain in my playlist, but songs added to my library will be added to the correct playlist.

Thanks!

**Comment by smartplaylistsquestion** [comment]
Hell yeah. Thanks again

**Comment by csmed** [comment]
Totally Awesome! Thanks for this. You rock!
