### ISSUE TITLE
Sorting Option

### ISSUE THREAD

**Issue by thomaskelly** [jamesfairhurst/smart-playlists-for-spotify#18]
Hi there. Thanks for building this app. It is crazy Spotify hasn’t done this already! Anyway, when I used to use iTunes smart playlists, I almost always applied a filter that sorted or created playlist according to songs I had played least recently. So you are essentially making sure you’re hearing all your tracks. Is that possible with your app? 
Thanks!

**Comment by jamesfairhurst** [comment]
Hey thanks for the feedback, unfortunately Spotify don't give that info in their api e.g. last played, how many times played etc :(

Did have the idea of grabbing that info from Last.fm if you linked your account but that's currently just an idea.
